_BASE_: "Base-SparseInst.yaml"
MODEL:
  # WEIGHTS: "pretrained_models/resnet50d_ra2-464e36ba.pth"
  WEIGHTS: "pretrained_models/sparse_inst_r50_dcn_giam_aug_cbd71c.pth"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_vd_backbone"
  RESNETS:
    DEFORM_ON_PER_STAGE: [False, False, True, True] # dcn on res4, res5
  SPARSE_INST:
    DECODER:
      NUM_CLASSES: 25
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MASK_FORMAT: "polygon"
OUTPUT_DIR: "output/sparse_inst_r50vd_dcn_giam_aug"

DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 100
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 200
  TEST:
  - ovis_test
  TRAIN:
  - ovis_train
  
DATALOADER:
  NUM_WORKERS: 2

SOLVER:
  IMS_PER_BATCH: 2

